version: "3.8"

services:
  frontend:
    build: 
      context: ./ 
      dockerfile: ./src/Dockerfile
    ports: 
      - 3000:3000
    depends_on: 
      - backend

  backend:
    build: 
      context: ./ 
      dockerfile: server/go/Dockerfile
    ports: 
      - 9090:9090
